name: fitness_gym_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.3
  flutter_svg: ^2.0.7
  dio: ^5.8.0+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  shimmer: ^3.0.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
