// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfqqqrXYQNLTpG9ug872izy-gzWP0pTiE',
    appId: '1:803183851925:web:5ffe306b472c16632dde9c',
    messagingSenderId: '803183851925',
    projectId: 'and-fitness-4e047',
    authDomain: 'and-fitness-4e047.firebaseapp.com',
    storageBucket: 'and-fitness-4e047.firebasestorage.app',
    measurementId: 'G-TPCX2B0XES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4QLbEFFVWGh-Z8FmML8ljqd_Vri7oIr8',
    appId: '1:803183851925:android:69863716636982562dde9c',
    messagingSenderId: '803183851925',
    projectId: 'and-fitness-4e047',
    storageBucket: 'and-fitness-4e047.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZnPzfomCNHiQuT8FKraYvXIjeFm0-ApI',
    appId: '1:803183851925:ios:4a9dab719afd20792dde9c',
    messagingSenderId: '803183851925',
    projectId: 'and-fitness-4e047',
    storageBucket: 'and-fitness-4e047.firebasestorage.app',
    iosBundleId: 'com.example.fitnessGymApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZnPzfomCNHiQuT8FKraYvXIjeFm0-ApI',
    appId: '1:803183851925:ios:4a9dab719afd20792dde9c',
    messagingSenderId: '803183851925',
    projectId: 'and-fitness-4e047',
    storageBucket: 'and-fitness-4e047.firebasestorage.app',
    iosBundleId: 'com.example.fitnessGymApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfqqqrXYQNLTpG9ug872izy-gzWP0pTiE',
    appId: '1:803183851925:web:b26d42240ef1da5c2dde9c',
    messagingSenderId: '803183851925',
    projectId: 'and-fitness-4e047',
    authDomain: 'and-fitness-4e047.firebaseapp.com',
    storageBucket: 'and-fitness-4e047.firebasestorage.app',
    measurementId: 'G-3LLKET1WH7',
  );
}
